name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # -------------------------
      # TERRAFORM
      # -------------------------
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          EC2_IP=$(terraform output -raw ec2_public_ip | head -n 1 | tr -d '\n')
          printf "ec2_ip=%s\n" "$EC2_IP" >> $GITHUB_OUTPUT
        working-directory: terraform

      # -------------------------
      # BUILD & PUSH
      # -------------------------
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 065636181497.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Tag image
        run: docker tag myapp:latest 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest

      - name: Push to ECR
        run: docker push 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest

      # -------------------------
      # DEPLOY
      # -------------------------
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i devops-key.pem ec2-user@$EC2_IP "
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 065636181497.dkr.ecr.ap-south-1.amazonaws.com &&
          docker stop myapp || true &&
          docker rm myapp || true &&
          docker pull 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest &&
          docker run -d -p 80:3000 --name myapp 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest
          "

      # -------------------------
      # CLEANUP (FINAL STEP)
      # -------------------------
      - name: Cleanup on failure
        if: failure()
        run: terraform destroy -auto-approve
        working-directory: terraform