name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform

  build-and-push:
    runs-on: ubuntu-latest
    needs: terraform   # 🔥 important (wait for infra)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 065636181497.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Tag image
      run: docker tag myapp:latest 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest

    - name: Push to ECR
      run: docker push 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 065636181497.dkr.ecr.ap-south-1.amazonaws.com

          docker stop myapp || true
          docker rm myapp || true

          docker pull 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest

          docker run -d -p 80:3000 --name myapp 065636181497.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest